fix(bin): dockerTTY should check tty file existed first

diff --git a/bin/dockerTTY b/bin/dockerTTY
--- a/bin/dockerTTY
+++ b/bin/dockerTTY
@@ -5,4 +5,11 @@ set -o nounset
 set -o pipefail
 (shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
 
-sudo ls -ahlF ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty | awk '{print $NF}'
+readonly tty_file=~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
+
+if [[ ! -e "$tty_file" ]]; then
+  echo "$tty_file not found"
+  exit 4
+fi
+
+sudo ls -ahlF "$tty_file" | awk '{print $NF}'
