update(bin/sub): update scripts for custom plugins

diff --git a/bin/sub/disable-plugin b/bin/sub/disable-plugin
--- a/bin/sub/disable-plugin
+++ b/bin/sub/disable-plugin
@@ -9,7 +9,22 @@ set -o pipefail
 [[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
 [[ $- =~ [x] ]] && PS4='+[${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}}()]: '
 
-readonly name=$1
+readonly args=("$@")
 
-unlink "$DOTFILE_DIR"/bash-custom/enabled/"$name".plugin.bash
-echo "$name".plugin.bash disabled
+check_plugin() {
+  local name=$1
+  if [[ ! -f "$DOTFILE_DIR"/bash-custom/enabled/"$name".plugin.bash ]]; then
+    echo "Not found plugin '$name' enabled" >&2
+    exit 1
+  fi
+}
+
+disable_plugin() {
+    unlink "$DOTFILE_DIR"/bash-custom/enabled/"$name".plugin.bash
+    echo "$name".plugin.bash disabled
+}
+
+for name in "${args[@]}"; do
+  check_plugin "$name"
+  disable_plugin "$name"
+done
